### ISSUE TITLE
gemspec has incorrect homepage link

### ISSUE THREAD

**Issue by mjy** [ruby-rdf/shacl#2]
When I navigate to https://rubygems.org/gems/shacl, and I click 'Homepage', then I get a 404 not found.

The bad line is https://github.com/ruby-rdf/shacl/blob/develop/shacl.gemspec#L9

It should read:   `gem.homepage           = 'https://github.com/shacl'`

**Comment by gkellogg** [comment]
Thanks, I noted the problem elsewhere as well. This error seems to exist on other managed gems, as well.

It should actually read `gem.homepage = 'https://github.com/ruby-rdf/shacl'`.

**Comment by gkellogg** [comment]
Fixed in 0.2.1 release.
